src/DailyImages/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pictures.urls", namespace="pictures")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

src/pictures/urls.py
from django.urls import path

from .views import home_view, create_view, edit_view, delete_view


app_name = "pictures"


urlpatterns = [
    path("", home_view, name="home"),
    path("create/", create_view, name="create"),
    path("edit/<pk>/", edit_view, name="edit"),
    path("delete/<pk>/", delete_view, name="delete"),
]

src/pictures/models.py
from django.db import models


class Picture(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="pictures_images")

    def __str__(self):
        return self.title

src/pictures/forms.py
from django import forms
from .models import Picture


class PictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ["title", "image"]

src/pictures/views.py
from django.shortcuts import redirect, render
from .models import Picture
from .forms import PictureForm


def home_view(request):
    picture_list = Picture.objects.all()[:20][::-1]
    context = {"picture_list": picture_list}
    return render(request, "pictures/home.html", context)


def create_view(request):
    form = PictureForm(
        data=request.POST or None, files=request.FILES or None
    )

    if request.method == "GET":
        context = {"form": form}
        return render(request, "pictures/create.html", context)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("pictures:home")
        context = {"form": form}
        return render(request, "pictures/create.html", context)


def edit_view(request, pk):
    queryset = Picture.objects.filter(pk=pk)
    if queryset.exists():
        picture = queryset.first()
    else:
        return redirect("pictures:home")

    form = PictureForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=picture,
    )

    if request.method == "GET":
        context = {"form": form}
        return render(request, "pictures/edit.html", context)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("pictures:home")
        context = {"form": form}
        return render(request, "pictures/edit.html", context)


def delete_view(request, pk):
    queryset = Picture.objects.filter(pk=pk)
    if queryset.exists():
        picture = queryset.first()
        picture.delete()
    return redirect("pictures:home")

src/pictures/templates/pictures/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>DailyImages</title>
	</head>
	<body>
		<div>
			<img src="{% static 'pictures/logo.jpg' %}" alt="" width="80" />
			<ul style="display: inline-block">
				<li><a href="{% url 'pictures:home' %}">Home</a></li>
				<li><a href="{% url 'pictures:create' %}">Create</a></li>
			</ul>
		</div>
		{% block content %}
		<div>Content here</div>
		{% endblock content %}
	</body>
</html>

src/pictures/templates/pictures/create.html
{% extends "pictures/base.html" %}

<div>
	{% block content %}
	<div>{% include "pictures/form.html" with form=form title="Add a new picture" button_text="Add" %}</div>
	{% endblock content %}
</div>

src/pictures/templates/pictures/edit.html
{% extends "pictures/base.html" %}

<div>
	{% block content %}
	<div>{% include "pictures/form.html" with form=form title="Edit picture" button_text="Edit" %}</div>
	{% endblock content %}
</div>

src/pictures/templates/pictures/form.html
<div style="padding: 50px; border: 2px solid gray; display: inline-block">
	<form method="POST" enctype="multipart/form-data">
		<legend>{{ title }}</legend>
		<div class="mb-3">{% csrf_token %} {{ form.as_p }}</div>
		<button class="btn btn-sm btn-dark" type="SUBMIT">{{ button_text }}</button>
	</form>
</div>

src/pictures/templates/pictures/home.html
{% extends "pictures/base.html" %}

<div>
	{% block content %}
	<div>
		{% for picture in picture_list %}
		<div style="margin-top: 40px">
			<h4>
				{{ picture.title }} | <a href="{% url 'pictures:edit' picture.id %}">edit</a> | <a href="{% url 'pictures:delete' picture.id %}">delete</a>
			</h4>
			<img src="{{ picture.image.url }}" alt="{{ picture.title }}" style="max-width: 100%" />
		</div>
		<hr />
		{% endfor %}
	</div>
	{% endblock content %}
</div>